nextinfoERP/urls.py
from django.conf.urls import patterns, include, url
from nextinfoERP.bands.views import *

from django.contrib import admin

urlpatterns = patterns('nextinfoERP.bands.views',


    url(r'^$', Home.as_view(), name='home'),
    url(r'^bands/$', BandList.as_view(), name='bands'),
    url(r'^bands/(?P<pk>\d+)/$', 'band_detail', name='band_detail'),
    url(r'^bandform/$', BandForm.as_view(), name='band_form'),
    url(r'^memberform/$', MemberForm.as_view(), name='member_form'),
    url(r'^contact/$', 'band_contact', name='contact'),
    url(r'^protected/$', 'protected_view', name='protected'),
    url(r'^accounts/login/$', 'message'),
    url(r'^admin/', include(admin.site.urls), name='admin'),

)

nextinfoERP/bands/models.py
from django.db import models


class Band(models.Model):

    """A model of a rock band."""
    name = models.CharField(max_length=200)
    can_rock = models.BooleanField(default=True)

    class Meta:
        ordering = ['name']
        verbose_name = 'band'
        verbose_name_plural = 'bands'

    def __str__(self):
        return self.name

    # count members by band
    # conta os membros por banda
    def get_members_count(self):
        return self.band.count()

    # retorna a url no formato /bands/1
    def get_band_detail_url(self):
        return u"/bands/%i" % self.id


class Member(models.Model):

    """A model of a rock band member."""
    name = models.CharField("Member's name", max_length=200)
    instrument = models.CharField(choices=(
        ('g', "Guitar"),
        ('b', "Bass"),
        ('d', "Drums"),
        ('v', "Vocal"),
        ('p', "Piano"),
    ),
        max_length=1
    )

    band = models.ForeignKey("Band", related_name='band')

    class Meta:
        ordering = ['name']
        verbose_name = 'member'
        verbose_name_plural = 'members'

    def __str__(self):
        return self.name

nextinfoERP/core/models.py
from django.db import models
from django.db.models import Sum, F
from django.utils.translation import ugettext_lazy as _
from django.utils.formats import number_format

ativo_lista = [('A', 'Ativo'), ('I', 'Inativo')]
tipo_pessoa = [('F', 'Fisica'), ('J', 'Juridica')]




class TimeStampedModel(models.Model):
    data_criacao = models.DateTimeField(
        _('criado em'), auto_now_add=True, auto_now=False)
    data_modificacao = models.DateTimeField(
        _('modificado em'), auto_now_add=False, auto_now=True)

    class Meta:
        abstract = True

class Ativo(TimeStampedModel):
    ativo = models.CharField(_(u'ativo'), max_length=15, choices= ativo_lista)
    class Meta:
        abstract = True


class Pessoa(Ativo):
    tipo_pessoa = models.CharField(_(u'tipo'), max_length=15, choices= tipo_pessoa)
    class Meta:
        ordering = ['ativo','tipo_pessoa']

class PessoaFisica(Pessoa):
    pessoa = models.ForeignKey('Pessoa',  verbose_name=_('pessoa'))
    nomeCompleto = models.CharField(_('Nome'), max_length=40)
    cpf = models.CharField(_('CPF'), max_length=11,unique=True)
    rg = models.CharField(_('RG'), max_length=11)
    class Meta:
        ordering = ['pessoa','nomeCompleto','cpf']

class PessoaJuridica(Pessoa):
    cnpj = models.CharField(_('Cnpj'), max_length=11,unique=True)
    site = models.CharField(_('Site'), max_length=20)
    nomeFantasia = models.CharField(_('NomeFantasia'), max_length=20)
    razaoSocial = models.CharField(_('RazaoSocial'), max_length=20)
    pessoa = models.ForeignKey('Pessoa', verbose_name=_('pessoa'))

    class Meta:
        ordering = ['cnpj','nomeFantasia']

nextinfoERP/bands/forms.py
from django import forms
from .models import Band, Member


class BandContactForm(forms.Form):
    subject = forms.CharField(max_length=100)
    message = forms.CharField(widget=forms.Textarea)
    sender = forms.EmailField()
    cc_myself = forms.BooleanField(required=False)

class BandForm(forms.ModelForm):

    class Meta:
        model = Band
        fields = '__all__' # Django>=1.8


class MemberForm(forms.ModelForm):

    class Meta:
        model = Member
        fields = '__all__'

nextinfoERP/bands/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.views.generic import CreateView, TemplateView, ListView
from django.core.urlresolvers import reverse_lazy
from .models import Band, Member
from .forms import BandContactForm, BandForm, MemberForm

def home(request):
    return render(request, 'home.html')

class Home(TemplateView):
    template_name = 'home.html'

def band_listing(request):
    """ A view of all bands. """
    bands = Band.objects.all()
    var_get_search = request.GET.get('search_box')
    if var_get_search is not None:
        bands = bands.filter(name__icontains=var_get_search)
    return render(request, 'bands/band_listing.html', {'bands': bands})

class BandList(ListView):
    template_name = 'bands/band_listing.html'
    model = Band
    context_object_name = 'bands'
    paginate_by = 5

def band_contact(request):
    """ A example of form """
    if request.method == 'POST':
        form = BandContactForm(request.POST)
    else:
        form = BandContactForm()
    return render(request, 'bands/band_contact.html', {'form': form})

def band_detail(request, pk):
    """ A view of all members by bands. """
    band = Band.objects.get(pk=pk)
    members = Member.objects.all().filter(band=band)
    context = {'members': members, 'band': band}
    return render(request, 'bands/band_detail.html', context)

@login_required(login_url='/accounts/login/')
def protected_view(request):
    """ A view that can only be accessed by logged-in users """
    return render(request, 'bands/protected.html', {'current_user': request.user})


def message(request):
    """ Message if is not authenticated. Simple view! """
    return HttpResponse('Access denied!')

class BandForm(CreateView):
    template_name = 'bands/band_form.html'
    form_class = BandForm
    success_url = reverse_lazy('bands')


class MemberForm(CreateView):
    template_name = 'bands/member_form.html'
    form_class = MemberForm
    success_url = reverse_lazy('bands')

nextinfoERP/core/views.py
from django.shortcuts import render

# Create your views here.

nextinfoERP/bands/templates/bands/band_contact.html
{% extends "base.html" %}

{% load bootstrap3 %}

{% block title %}
    <title>Band Contact</title>
{% endblock title %}

{% block content %}

    <h1>Send e-mail</h1>
    <form class="form" method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button type="submit" class="btn btn-primary">{% bootstrap_icon "star" %} Submit</button>
        {% endbuttons %}
    </form>

{% endblock content %}

nextinfoERP/bands/templates/bands/band_detail.html
{% extends "base.html" %}

{% block title %}
    <title>Member Listing</title>
{% endblock title %}

{% block content %}
    <h2>Members of {{ band.name }}</h2>
    <ul class="list-group">
        {% for member in members %}
            {% if member.instrument == 'v' %}
                <li class="list-group-item list-group-item-info">
            {% else %}
                <li class="list-group-item">
            {% endif %}
                    {{ member.name }} - {{ member.get_instrument_display }}
                </li>
        {% endfor %}
    </ul>
{% endblock content %}

nextinfoERP/bands/templates/bands/band_form.html
{% extends "base.html" %}

{% load bootstrap3 %}

{% block title %}
    <title>Band Form</title>
{% endblock title %}

{% block content %}

    <h1>Create band</h1>
    <form class="form col-sm-4" method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button type="submit" class="btn btn-primary">Submit</button>
        {% endbuttons %}
    </form>

{% endblock content %}

nextinfoERP/bands/templates/bands/band_listing.html
{% extends "base.html" %}

{% block title %}
    <title>Band Listing</title>
{% endblock title %}

{% block content %}
    <!-- search form -->
    <form class="navbar-form navbar-right" action="." method="get">
        <input id="search_box" name="search_box" type="text" placeholder="Search..." class="form-control">
        <button type="submit" class="btn btn-success form-control"><span class="glyphicon glyphicon-search"></span></button>
    </form>

    <h1>All Bands</h1>
    {% for band in bands %}
        <ul class="list-group">
          <li class="list-group-item">
            <span class="badge">{{ band.get_members_count }}</span>
            <h4><a href="{{ band.get_band_detail_url }}">{{ band.name }}</a></h4>
            {% if band.can_rock %}
                <p>This band can rock!</p>
            {% endif %}
          </li>
        </ul>
    {% endfor %}
{% endblock content %}

nextinfoERP/bands/templates/bands/member_form.html
{% extends "base.html" %}

{% load bootstrap3 %}

{% block title %}
    <title>Member Form</title>
{% endblock title %}

{% block content %}

    <h1>Create member</h1>
    <form class="form col-sm-4" method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button type="submit" class="btn btn-primary">Submit</button>
        {% endbuttons %}
    </form>

{% endblock content %}

nextinfoERP/bands/templates/bands/protected.html
{% extends "base.html" %}

{% block title %}
    <title>Protected</title>
{% endblock title %}

{% block content %}
    <h1>Protected page</h1>

    <p>Logged as: {{ user }}</p>
{% endblock content %}

nextinfoERP/bands/templates/base.html
<html>
<head>
    {% load bootstrap3 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}

  <link rel="icon" href="http://s3.amazonaws.com/snaaakes-static/img/colophon/django.png">


    {% block title %}
        <title>Django 1.7</title>
    {% endblock title %}

  <style>
    body {
      padding-top: 70px;
    }
  </style>

</head>

<body>

  {% include "menu.html" %}

  <div class="container">
    {% block content %}

    {% endblock content %}
  </div>

  {% block javascript %}
    <!-- Latest JQuery -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>

    <!-- Latest compiled and minified JavaScript -->
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
  {% endblock javascript %}

</body>
</html>

nextinfoERP/bands/templates/home.html
{% extends "base.html" %}

{% block content %}
<div class="jumbotron">
    <h1>Bem vindo ao site!</h1>
    <p>Este site é um exemplo da introdução ao <a href="https://www.djangoproject.com">Django</a> que está escrito em <a href="https://www.djangoproject.com/start/">Intro to Django</a>.</p>
</div>
{% endblock content %}

nextinfoERP/bands/templates/menu.html
<!-- Menu -->
<div class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'home' %}">Home</a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><a href="{% url 'bands' %}">Bands</a></li>
        <li><a href="{% url 'contact' %}">Contact</a></li>
        <li><a href="{% url 'protected' %}">Protected</a></li>
        <!-- to resolve NoReverseMatch for 'admin' -->
        <li><a href="{% url 'admin:index' %}">Login</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Create<b class="caret"></b></a>
          <ul class="dropdown-menu">
           <li><a href="{% url 'band_form' %}">Create band</a></li>
           <li><a href="{% url 'member_form' %}">Create member</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</div>